import {
  Accessibility,
  Armchair,
  Baby,
  Bed,
  Building2,
  Camera,
  Car,
  CheckCircle,
  Clock3,
  Dumbbell,
  Flame,
  Flower2,
  Home,
  KeyRound,
  Leaf,
  LockKeyhole,
  MapPin,
  PawPrint,
  ShieldCheck,
  Sparkles,
  Sun,
  Trees,
  Users,
  Waves,
  Wifi,
  Zap,
  CircleHelp,
} from "lucide-react";

export const amenityIconOptions = [
  { key: "accessibility", label: "Accessibility", icon: Accessibility },
  { key: "armchair", label: "Lounge / Seating", icon: Armchair },
  { key: "baby", label: "Children", icon: Baby },
  { key: "bed", label: "Bedroom", icon: Bed },
  { key: "building", label: "Building", icon: Building2 },
  { key: "camera", label: "CCTV / Camera", icon: Camera },
  { key: "car", label: "Parking / Vehicle", icon: Car },
  { key: "check-circle", label: "General Feature", icon: CheckCircle },
  { key: "clock", label: "24/7 / Time", icon: Clock3 },
  { key: "dumbbell", label: "Fitness / Gym", icon: Dumbbell },
  { key: "flame", label: "Fire / BBQ", icon: Flame },
  { key: "flower", label: "Garden / Plants", icon: Flower2 },
  { key: "home", label: "Home", icon: Home },
  { key: "key", label: "Access / Keys", icon: KeyRound },
  { key: "leaf", label: "Nature / Eco", icon: Leaf },
  { key: "lock", label: "Security / Lock", icon: LockKeyhole },
  { key: "map-pin", label: "Location", icon: MapPin },
  { key: "paw", label: "Pets", icon: PawPrint },
  { key: "shield", label: "Security", icon: ShieldCheck },
  { key: "sparkles", label: "Luxury / Premium", icon: Sparkles },
  { key: "sun", label: "Outdoor / Rooftop", icon: Sun },
  { key: "trees", label: "Garden / Green Space", icon: Trees },
  { key: "users", label: "Community / Social", icon: Users },
  { key: "waves", label: "Pool / Water", icon: Waves },
  { key: "wifi", label: "Internet / Wi-Fi", icon: Wifi },
  { key: "zap", label: "Power / Electricity", icon: Zap },
  { key: "default", label: "Default", icon: CircleHelp },
];

export const amenityIcons = Object.fromEntries(
  amenityIconOptions.map(({ key, icon }) => [key, icon])
);